import base64
import io

from odoo import api, fields, models, _
from odoo.exceptions import UserError

try:
    from pypdf import PdfReader, PdfWriter
except ImportError:  # Odoo environments that still expose the legacy package
    from PyPDF2 import PdfReader, PdfWriter


SIGNATURE_STATES = [
    ("draft", "Not Sent"),
    ("pending", "Signing in Progress"),
    ("director_pending", "Legacy: Pending Director Signature"),
    ("ceo_pending", "Legacy: Pending CEO Signature"),
    ("signed", "Fully Signed"),
    ("rejected", "Rejected"),
]
ACTIVE_SIGNATURE_STATES = {"pending", "director_pending", "ceo_pending", "signed", "rejected"}


class PurchaseOrder(models.Model):
    _inherit = "purchase.order"

    sign_template_id = fields.Many2one("sign.template", copy=False, readonly=True)
    sign_request_id = fields.Many2one("sign.request", copy=False, readonly=True)
    signing_workflow_id = fields.Many2one("absar.sign.workflow", copy=False, readonly=True)
    signature_state = fields.Selection(SIGNATURE_STATES, default="draft", tracking=True, copy=False)
    signature_status_text = fields.Char(default="Not Sent", copy=False, readonly=True)
    signature_completed_count = fields.Integer(default=0, copy=False, readonly=True)
    signature_total_count = fields.Integer(default=0, copy=False, readonly=True)
    revision = fields.Integer(default=0, tracking=True, copy=False)
    quotation_attachment_ids = fields.Many2many(
        "ir.attachment",
        "purchase_order_sign_quotation_attachment_rel",
        "purchase_order_id",
        "attachment_id",
        string="Supplier Quotation PDF(s)",
        copy=False,
        help="Select the supplier quotation PDF attachment(s) to append after the PO and before the linked Material Request in the signing package.",
    )

    project_id = fields.Many2one("project.project", string="Project", tracking=True, groups=False)

    def _reset_signing(self, reason):
        for po in self:
            if po.signature_state not in ACTIVE_SIGNATURE_STATES:
                continue
            revision = (po.revision or 0) + 1
            po.with_context(skip_po_sign_reset=True).write({
                "revision": revision,
                "signature_state": "draft",
                "signature_status_text": _("Not Sent"),
                "signature_completed_count": 0,
                "signature_total_count": 0,
                "sign_template_id": False,
                "sign_request_id": False,
                "signing_workflow_id": False,
            })
            po.message_post(body=_("%s Reset to Not Sent (Revision R%s).") % (reason, revision))

    def write(self, vals):
        previous = {po.id: po.signature_state for po in self}
        res = super().write(vals)
        if self.env.context.get("skip_po_sign_reset"):
            return res
        meaningful = {"amount_total", "date_planned", "date_approve", "partner_id", "currency_id", "notes", "project_id"}
        if meaningful.intersection(vals):
            for po in self:
                if previous.get(po.id) in ACTIVE_SIGNATURE_STATES:
                    po._reset_signing(_("PO modified after signing/sending."))
        return res

    def _absar_render_linked_material_request_pdf(self):
        self.ensure_one()
        if not hasattr(self, "material_request_id") or not self.material_request_id:
            return None
        mr = self.material_request_id
        reports = self.env["ir.actions.report"].sudo().search([
            ("model", "=", mr._name),
            ("report_type", "=", "qweb-pdf"),
        ])
        if not reports:
            raise UserError(_("The linked Material Request has no PDF report configured, so the signing package cannot include it."))
        report = reports.filtered(lambda r: "material" in (r.name or "").lower() and "request" in (r.name or "").lower())[:1] or reports[:1]
        pdf_content, _fmt = report._render_qweb_pdf(report.report_name, mr.ids)
        return pdf_content

    def _absar_get_quotation_attachments(self):
        """Return quotation PDFs for the signing package.

        Explicit selections win. If none are selected, reuse quotation PDFs that
        are already attached to the PO chatter. This keeps the normal user flow:
        upload the supplier quotation in chatter, then Send to Sign.
        """
        self.ensure_one()
        if self.quotation_attachment_ids:
            return self.quotation_attachment_ids

        attachments = self.env["ir.attachment"].sudo().search([
            ("res_model", "=", "purchase.order"),
            ("res_id", "=", self.id),
            ("mimetype", "=", "application/pdf"),
        ], order="id asc")

        # Ignore documents generated by the signing engine itself, if any.
        if self.sign_template_id and self.sign_template_id.attachment_id:
            attachments = attachments - self.sign_template_id.attachment_id

        if not attachments:
            return attachments
        if len(attachments) == 1:
            return attachments

        # When several PDFs exist in chatter, prefer files that clearly look like
        # supplier quotations instead of silently merging unrelated documents.
        keywords = ("quotation", "quote", "offer", "proposal", "عرض", "تسعير")
        likely = attachments.filtered(
            lambda a: any(keyword in (a.name or "").lower() for keyword in keywords)
        )
        if likely:
            return likely

        raise UserError(_(
            "Several PDF attachments are present on this Purchase Order. "
            "Please select the supplier quotation(s) in the Signing Package tab "
            "before sending to Sign."
        ))

    def _absar_build_signing_package_pdf(self):
        self.ensure_one()
        po_pdf, _fmt = self.env["ir.actions.report"]._render_qweb_pdf(
            "purchase.report_purchaseorder", self.ids
        )
        parts = [("Purchase Order", po_pdf)]

        for attachment in self._absar_get_quotation_attachments():
            if attachment.mimetype != "application/pdf":
                raise UserError(_("Quotation attachment '%s' is not a PDF.") % attachment.name)
            if not attachment.datas:
                raise UserError(_("Quotation attachment '%s' has no file content.") % attachment.name)
            parts.append((attachment.name or _("Supplier Quotation"), base64.b64decode(attachment.datas)))

        mr_pdf = self._absar_render_linked_material_request_pdf()
        if mr_pdf:
            parts.append((_("Material Request"), mr_pdf))

        writer = PdfWriter()
        try:
            for label, content in parts:
                reader = PdfReader(io.BytesIO(content))
                for page in reader.pages:
                    writer.add_page(page)
            output = io.BytesIO()
            writer.write(output)
            return output.getvalue()
        except Exception as exc:
            raise UserError(_("Could not build the PO signing package (PO → Quotation → MR): %s") % exc) from exc

    def action_send_to_sign(self):
        self.ensure_one()
        if self.state != "purchase":
            raise UserError(_("Only a confirmed Purchase Order can be sent to Sign."))
        if self.signature_state != "draft":
            raise UserError(_("This Purchase Order has already been sent to Sign."))

        package_pdf = self._absar_build_signing_package_pdf()
        template, workflow, status = self.env["absar.sign.workflow.service"].create_template(
            self,
            "purchase.report_purchaseorder",
            self.name,
            [
                self.partner_id.name,
                self.material_request_id.name if hasattr(self, "material_request_id") and self.material_request_id else None,
                self.project_id.name if self.project_id else None,
            ],
            pdf_content=package_pdf,
        )
        # Keep the generated PDF/attachment aligned with the visible Sign template name.
        if template.attachment_id:
            template.attachment_id.sudo().name = f"{template.name}.pdf"

        self.with_context(skip_po_sign_reset=True).write({
            "sign_template_id": template.id,
            "signing_workflow_id": workflow.id,
            "signature_state": "pending",
            "signature_status_text": status,
            "signature_completed_count": 0,
            "signature_total_count": len(workflow.step_ids),
        })
        first = workflow.step_ids.sorted("sequence")[0]
        self.message_post(
            body=_("PO prepared for signing. Workflow: %(workflow)s. First signer: %(role)s (%(user)s).") % {
                "workflow": workflow.name,
                "role": first.name,
                "user": first.signer_user_id.name,
            }
        )
        return {
            "type": "ir.actions.act_url",
            "url": f'/odoo/sign/{template.id}/action-sign.Template?id={template.id}&name=Template%20"PO%20{self.name}"',
            "target": "self",
        }

    def action_open_signature_status(self):
        self.ensure_one()
        return self.env["absar.sign.workflow.service"].open_status(self)

    @api.model
    def _absar_migrate_legacy_signatures(self):
        """Backfill POs signed before the configurable signing engine.

        Legacy versions already stored sign_template_id/signature_state but did
        not have sign_request_id or the new status/count fields.  Preserve the
        historical result and link the newest request where available.
        """
        service = self.env["absar.sign.workflow.service"].sudo()
        Request = self.env["sign.request"].sudo()
        Item = self.env["sign.request.item"].sudo()
        pos = self.sudo().search([("sign_template_id", "!=", False)])

        def item_completed(item):
            if "state" in item._fields and item.state in ("completed", "signed"):
                return True
            return any(
                field_name in item._fields and bool(item[field_name])
                for field_name in ("is_signed", "signed", "completed")
            )

        for po in pos:
            request = Request.search(
                [("template_id", "=", po.sign_template_id.id)],
                order="id desc",
                limit=1,
            )
            vals = {}
            if request and not po.sign_request_id:
                vals["sign_request_id"] = request.id

            # Historical signed state is authoritative.  Also detect a fully
            # signed Odoo Sign request in case an earlier upgrade left the PO
            # state/status text at its new default.
            request_signed = bool(request and request.state == "signed")
            if po.signature_state == "signed" or request_signed:
                items = Item.search([("sign_request_id", "=", request.id)]) if request else Item.browse()
                total = len(items)
                completed = len(items.filtered(item_completed))
                if po.signing_workflow_id:
                    total = max(total, len(po.signing_workflow_id.step_ids))
                vals.update({
                    "signature_state": "signed",
                    "signature_status_text": _("Fully Signed"),
                    "signature_completed_count": max(completed, total),
                    "signature_total_count": total,
                })
            elif request:
                # For old pending requests, let the current engine calculate the
                # live progress and waiting signer using the actual Sign request.
                if vals:
                    po.with_context(skip_po_sign_reset=True).write(vals)
                service.sync_record(po, "skip_po_sign_reset")
                continue
            elif po.signature_state in ("director_pending", "ceo_pending"):
                vals.update({
                    "signature_state": "pending",
                    "signature_status_text": _("Template Ready · Awaiting Send"),
                })

            if vals:
                po.with_context(skip_po_sign_reset=True).write(vals)
        return True

    @api.model
    def _cron_sync_sign_status(self):
        records = self.search([
            ("sign_template_id", "!=", False),
            ("signature_state", "in", ["pending", "director_pending", "ceo_pending"]),
        ])
        service = self.env["absar.sign.workflow.service"]
        for po in records:
            service.sync_record(po, "skip_po_sign_reset")


class PurchaseOrderLine(models.Model):
    _inherit = "purchase.order.line"

    def write(self, vals):
        states = {line.order_id.id: line.order_id.signature_state for line in self}
        res = super().write(vals)
        meaningful = {"product_qty", "price_unit", "product_id", "date_planned", "discount", "taxes_id", "product_uom"}
        if not self.env.context.get("skip_po_sign_reset") and meaningful.intersection(vals):
            for order in self.mapped("order_id"):
                if states.get(order.id) in ACTIVE_SIGNATURE_STATES:
                    order._reset_signing(_("PO line modified after signing/sending."))
        return res

    @api.model_create_multi
    def create(self, vals_list):
        records = super().create(vals_list)
        if not self.env.context.get("skip_po_sign_reset"):
            for order in records.mapped("order_id"):
                if order.signature_state in ACTIVE_SIGNATURE_STATES:
                    order._reset_signing(_("PO line added after signing/sending."))
        return records

    def unlink(self):
        orders = {line.order_id.id: (line.order_id, line.order_id.signature_state) for line in self}
        res = super().unlink()
        if not self.env.context.get("skip_po_sign_reset"):
            for order, state in orders.values():
                if state in ACTIVE_SIGNATURE_STATES:
                    order._reset_signing(_("PO line removed after signing/sending."))
        return res
